language: php

php:
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION="2.*"
  - SYMFONY_VERSION="3.*"

install:
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION}
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer require symfony/config:${SYMFONY_VERSION}
  - composer require symfony/dependency-injection:${SYMFONY_VERSION}
  - composer install --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "demateus@gmail.com"